# Generated by Django 5.2.4 on 2025-07-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_alter_problem_difficulty_alter_problem_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(choices=[('a', 'Easy'), ('b', 'Medium'), ('c', 'Hard')], max_length=20),
        ),
    ]
