# Generated by Django 5.2.4 on 2025-08-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_alter_problem_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='expected_output',
            field=models.TextField(default='Hello Alice'),
            preserve_default=False,
        ),
    ]
